name: Latest blog post workflow
on:
  schedule:
    # S'exécute automatiquement toutes les 6 heures
    - cron: '0 */6 * * *'
  workflow_dispatch: # Te permet de le lancer manuellement depuis l'onglet Actions

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    
    # Donne l'autorisation au workflow de modifier le contenu de ton dépôt (ton README)
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://rpmn0ise.github.io/feed.xml"
          max_post_count: 4
          template: "- [$title]($url) · <kbd>$date</kbd>"
          date_format: "mmm d, yyyy"
